version: '3.1'
services:
  security:
    build: ./service
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./service:/app
  db:
    build: ./mysql-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306